#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):
    sortedList = sorted(a, reverse=True)
    alice = sum([j for i, j in enumerate(sortedList) if i % 2 == 0])
    bob = sum([j for i, j in enumerate(sortedList) if i % 2 == 1])
    print(alice - bob)
    return


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
